default: &default
  encoding: utf8
  pool: 15

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_45700_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: furima_45700_test

production:
  <<: *default
  adapter: mysql2
  database: furima_45700_production
  username: root
  password: <%= ENV['DATABASE_PASSWORD'] %>
  socket: /var/lib/mysql/mysql.sock